Get some more info hopefully.

diff --git a/bin/steps/collectstatic b/bin/steps/collectstatic
--- a/bin/steps/collectstatic
+++ b/bin/steps/collectstatic
@@ -11,22 +11,26 @@ if [ ! "$DISABLE_COLLECTSTATIC" ] && [ -f "$MANAGE_FILE" ]; then
     set +e
 
     # Check if collectstatic is configured properly.
-    python $MANAGE_FILE collectstatic --dry-run --noinput &> /dev/null && RUN_COLLECTSTATIC=true
-    python $MANAGE_FILE bower_install
-    python $MANAGE_FILE collectstatic --noinput
+    # python $MANAGE_FILE collectstatic --dry-run --noinput &> /dev/null && RUN_COLLECTSTATIC=true
+
+    echo "-------> bower install"
+    python $MANAGE_FILE bower_install --traceback
+
+    echo "-------> collect static"
+    python $MANAGE_FILE collectstatic --noinput --traceback
 
     # Compile assets if collectstatic appears to be kosher.
-    if [ "$RUN_COLLECTSTATIC" ]; then
+    # if [ "$RUN_COLLECTSTATIC" ]; then
 
-        echo "-----> Collecting static files"
-        python $MANAGE_FILE bower_install 2>&1 | sed '/^bower install/d;/^$/d;/^ /d' | indent
-        python $MANAGE_FILE collectstatic --noinput  2>&1 | sed '/^Copying/d;/^$/d;/^ /d' | indent
+    #     echo "-----> Collecting static files"
+    #     python $MANAGE_FILE bower_install 2>&1 | sed '/^bower install/d;/^$/d;/^ /d' | indent
+    #     python $MANAGE_FILE collectstatic --noinput  2>&1 | sed '/^Copying/d;/^$/d;/^ /d' | indent
 
-        [ $? -ne 0 ] && {
-            echo " !     Error running manage.py collectstatic. More info:"
-            echo "       http://devcenter.heroku.com/articles/django-assets"
-        }
-    fi
+    #     [ $? -ne 0 ] && {
+    #         echo " !     Error running manage.py collectstatic. More info:"
+    #         echo "       http://devcenter.heroku.com/articles/django-assets"
+    #     }
+    # fi
 
     echo
 
